"""Registration keys every pyhighlights configuration is addressed by."""

from cinnamon.registry import RegistrationKey

NAMESPACE = "pyhighlights"


def key(name: str, *tags: str) -> RegistrationKey:
    return RegistrationKey(name=name, tags=set(tags), namespace=NAMESPACE)


BEER = key("dataset", "beer")
HOTEL = key("dataset", "hotel")
MOVIES = key("dataset", "movies")
HATEXPLAIN = key("dataset", "hatexplain")
TOY = key("dataset", "toy")
LEAKAGE_DETECTOR = key("detector", "leakage")
LEAKAGE_REMOVER = key("preprocessor", "leakage")
HATEXPLAIN_AGGREGATOR = key("preprocessor", "aggregator", "hatexplain")
PIPELINE = key("preprocessor", "pipeline")
HATEXPLAIN_PIPELINE = key("preprocessor", "pipeline", "hatexplain")
GRU_BACKBONE = key("backbone", "gru")
GENSPP_GRU_BACKBONE = key("backbone", "genspp", "gru")
TRANSFORMER_BACKBONE = key("backbone", "transformer")
GENSPP_TRANSFORMER_BACKBONE = key("backbone", "genspp", "transformer")
MLP_SELECTOR = key("selector", "mlp")
MLP_PREDICTOR = key("predictor", "mlp")
GRU_GUIDER = key("guider", "attention", "gru")
TRANSFORMER_GUIDER = key("guider", "attention", "transformer")
TOY_TASK = key("task", "toy")
TOY_GENSPP_TASK = key("task", "genspp", "toy")
TOY_BENCHMARK = key("benchmark", "toy")
METRICS_ANALYZER = key("analyzer", "metrics")
HIGHLIGHT_POSITION_ANALYZER = key("analyzer", "position", "highlight")
PREDICTION_ANALYZER = key("analyzer", "prediction")
LABEL_STUDIO_EXPORTER = key("analyzer", "label-studio")
ACCURACY = key("torchmetric", "accuracy")
MULTICLASS_ACCURACY = key("torchmetric", "accuracy", "multiclass")
F1 = key("torchmetric", "f1")
MULTICLASS_F1 = key("torchmetric", "f1", "multiclass")
HIGHLIGHT_F1 = key("torchmetric", "f1", "highlight")
HIGHLIGHT_IOU = key("torchmetric", "iou", "highlight")
SELECTION_RATE = key("torchmetric", "selection_rate")
SELECTION_SIZE = key("torchmetric", "selection_size")
ACCURACY_METRIC = key("metric", "accuracy")
MULTICLASS_ACCURACY_METRIC = key("metric", "accuracy", "multiclass")
F1_METRIC = key("metric", "f1")
MULTICLASS_F1_METRIC = key("metric", "f1", "multiclass")
HIGHLIGHT_F1_METRIC = key("metric", "f1", "highlight")
HIGHLIGHT_IOU_METRIC = key("metric", "iou", "highlight")
SELECTION_RATE_METRIC = key("metric", "selection_rate")
SELECTION_SIZE_METRIC = key("metric", "selection_size")
CROSS_ENTROPY = key("criterion", "cross_entropy")
MASKED_CROSS_ENTROPY = key("criterion", "masked_cross_entropy")
MASKED_BCE = key("criterion", "masked_bce")
KL_DIV = key("criterion", "kl_div")
JS_DIV = key("criterion", "js_div")
SPARSITY_PENALTY = key("criterion", "sparsity")
CONTIGUITY_PENALTY = key("criterion", "contiguity")
CLASSIFICATION_LOSS = key("loss", "classification")
FULL_CLASSIFICATION_LOSS = key("loss", "classification", "full")
HIGHLIGHT_LOSS = key("loss", "highlight")
SPARSITY_LOSS = key("loss", "sparsity")
CONTIGUITY_LOSS = key("loss", "contiguity")
DISCREPANCY_LOSS = key("loss", "discrepancy")
GUIDE_LOSS = key("loss", "guide")
JSD_LOSS = key("loss", "jsd")
ADAM = key("optimizer", "adam")
GENSPP_ADAM = key("optimizer", "adam", "genspp")
GRU_FR = key("model", "fr", "gru")
GRU_GENSPP = key("model", "genspp", "gru")
GRU_GENSPP_TRAINER = key("trainer", "genspp", "gru")
TOY_GENSPP_TRAINER = key("trainer", "genspp", "gru", "toy")
GRU_MGR = key("model", "mgr", "gru")
GRU_MCD = key("model", "mcd", "gru")
GRU_GRAT = key("model", "grat", "gru")
TRANSFORMER_FR = key("model", "fr", "transformer")
TRANSFORMER_GENSPP = key("model", "genspp", "transformer")
TRANSFORMER_GENSPP_TRAINER = key("trainer", "genspp", "transformer")
TRANSFORMER_MGR = key("model", "mgr", "transformer")
TRANSFORMER_MCD = key("model", "mcd", "transformer")
TRANSFORMER_GRAT = key("model", "grat", "transformer")
