"""Registration keys every pyhighlights configuration is addressed by."""

from cinnamon.registry import RegistrationKey

NAMESPACE = "pyhighlights"


def key(name: str, *tags: str) -> RegistrationKey:
    return RegistrationKey(name=name, tags=set(tags), namespace=NAMESPACE)


BEER = key("dataset", "beer")
HOTEL = key("dataset", "hotel")
MOVIES = key("dataset", "movies")
HATEXPLAIN = key("dataset", "hatexplain")
TOY = key("dataset", "toy")
LEAKAGE_DETECTOR = key("detector", "leakage")
LEAKAGE_REMOVER = key("preprocessor", "leakage")
HATEXPLAIN_AGGREGATOR = key("preprocessor", "aggregator", "hatexplain")
CLASS_WEIGHTS = key("preprocessor", "class_weights")
PIPELINE = key("preprocessor", "pipeline")
HATEXPLAIN_PIPELINE = key("preprocessor", "pipeline", "hatexplain")
GRU_BACKBONE = key("backbone", "gru")
GENSPP_GRU_BACKBONE = key("backbone", "genspp", "gru")
TRANSFORMER_BACKBONE = key("backbone", "transformer")
FROZEN_TRANSFORMER_BACKBONE = key("backbone", "transformer", "frozen")
STACKED_BACKBONE = key("backbone", "transformer", "gru")
GENSPP_TRANSFORMER_BACKBONE = key("backbone", "genspp", "transformer")
MLP_SELECTOR = key("selector", "mlp")
MLP_PREDICTOR = key("predictor", "mlp")
ENTAILMENT_COMPARER = key("comparer", "entailment")
GRU_GUIDER = key("guider", "attention", "gru")
TRANSFORMER_GUIDER = key("guider", "attention", "transformer")
TOY_TASK = key("task", "toy")
TOY_CLASS_WEIGHTS_TASK = key("task", "class_weights", "toy")
TOY_GENSPP_TASK = key("task", "genspp", "toy")
TOY_BENCHMARK = key("benchmark", "toy")
METRICS_ANALYZER = key("analyzer", "metrics")
HIGHLIGHT_POSITION_ANALYZER = key("analyzer", "position", "highlight")
PREDICTION_ANALYZER = key("analyzer", "prediction")
LABEL_STUDIO_EXPORTER = key("analyzer", "label-studio")
ACCURACY = key("torchmetric", "accuracy")
MULTICLASS_ACCURACY = key("torchmetric", "accuracy", "multiclass")
F1 = key("torchmetric", "f1")
MULTICLASS_F1 = key("torchmetric", "f1", "multiclass")
CLASS_F1 = key("torchmetric", "f1", "class")
HIGHLIGHT_F1 = key("torchmetric", "f1", "highlight")
HIGHLIGHT_IOU = key("torchmetric", "iou", "highlight")
SELECTION_RATE = key("torchmetric", "selection_rate")
SELECTION_SIZE = key("torchmetric", "selection_size")
ACCURACY_METRIC = key("metric", "accuracy")
MULTICLASS_ACCURACY_METRIC = key("metric", "accuracy", "multiclass")
F1_METRIC = key("metric", "f1")
MULTICLASS_F1_METRIC = key("metric", "f1", "multiclass")
CLASS_F1_METRIC = key("metric", "f1", "class")
HIGHLIGHT_F1_METRIC = key("metric", "f1", "highlight")
HIGHLIGHT_IOU_METRIC = key("metric", "iou", "highlight")
SELECTION_RATE_METRIC = key("metric", "selection_rate")
SELECTION_SIZE_METRIC = key("metric", "selection_size")
CROSS_ENTROPY = key("criterion", "cross_entropy")
MASKED_CROSS_ENTROPY = key("criterion", "masked_cross_entropy")
MASKED_BCE = key("criterion", "masked_bce")
KL_DIV = key("criterion", "kl_div")
JS_DIV = key("criterion", "js_div")
SPARSITY_PENALTY = key("criterion", "sparsity")
CONTIGUITY_PENALTY = key("criterion", "contiguity")
CLASSIFICATION_LOSS = key("loss", "classification")
FULL_CLASSIFICATION_LOSS = key("loss", "classification", "full")
COMPLEMENT_CLASSIFICATION_LOSS = key("loss", "classification", "complement")
ALIGNMENT_CLASSIFICATION_LOSS = key("loss", "classification", "alignment")
HIGHLIGHT_LOSS = key("loss", "highlight")
SPARSITY_LOSS = key("loss", "sparsity")
CONTIGUITY_LOSS = key("loss", "contiguity")
KNOWLEDGE_LOSS = key("loss", "knowledge")
KNOWLEDGE_SPARSITY_LOSS = key("loss", "sparsity", "knowledge")
DISCREPANCY_LOSS = key("loss", "discrepancy")
REMAINING_DISCREPANCY_LOSS = key("loss", "discrepancy", "remaining")
GUIDE_LOSS = key("loss", "guide")
JSD_LOSS = key("loss", "jsd")
ADAM = key("optimizer", "adam")
GENSPP_ADAM = key("optimizer", "adam", "genspp")
GRU_FR = key("model", "fr", "gru")
GRU_GROUNDED = key("model", "grounded", "gru")
TRANSFORMER_GROUNDED = key("model", "grounded", "transformer")
GRU_GENSPP = key("model", "genspp", "gru")
GRU_GENSPP_TRAINER = key("trainer", "genspp", "gru")
TOY_GENSPP_TRAINER = key("trainer", "genspp", "gru", "toy")
GRU_DAR = key("model", "dar", "gru")
GRU_DR = key("model", "dr", "gru")
GRU_MGR = key("model", "mgr", "gru")
GRU_MRD = key("model", "mrd", "gru")
GRU_MCD = key("model", "mcd", "gru")
GRU_GRAT = key("model", "grat", "gru")
TRANSFORMER_FR = key("model", "fr", "transformer")
TRANSFORMER_GENSPP = key("model", "genspp", "transformer")
TRANSFORMER_GENSPP_TRAINER = key("trainer", "genspp", "transformer")
TRANSFORMER_DAR = key("model", "dar", "transformer")
TRANSFORMER_DR = key("model", "dr", "transformer")
TRANSFORMER_MGR = key("model", "mgr", "transformer")
TRANSFORMER_MRD = key("model", "mrd", "transformer")
TRANSFORMER_MCD = key("model", "mcd", "transformer")
TRANSFORMER_GRAT = key("model", "grat", "transformer")

#: What a run is monitored by. A study configures these the way it configures
#: its losses: early stopping and checkpointing on the same quantity, and a
#: criterion that turns two quantities into the one they have to agree on.
LOSS_EARLY_STOPPING = key("callback", "early_stopping", "loss")
LOSS_CHECKPOINT = key("callback", "checkpoint", "loss")
SCORE_EARLY_STOPPING = key("callback", "early_stopping", "score")
SCORE_CHECKPOINT = key("callback", "checkpoint", "score")
GENERALIZATION_LOSS_SCORE = key("callback", "score", "generalization_loss")
